### ISSUE TITLE
Into causing error line 130 of main.nf

### ISSUE THREAD

**Issue by aboyd003** [nf-core/cageseq#61]
Operator `into` has been deprecated -- it's not available in DSL2 syntax

 -- Check script '/rhome/aboyd003/.nextflow/assets/nf-core/cageseq/main.nf' at line: 130

**Comment by aboyd003** [comment]
More details in case they are helpful.

N E X T F L O W  ~  version 22.04.0
Run using singularity on hpcc cluster
Error details from log file:
Apr-30 16:54:21.810 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.DeprecationException: Operator `into` has been deprecated -- it's not available in DSL2 syntax
	at nextflow.extension.OpCall.checkDeprecation(OpCall.groovy:333)
	at nextflow.extension.OpCall.invoke1(OpCall.groovy:319)
	at nextflow.extension.OpCall.invoke0(OpCall.groovy:306)
	at nextflow.extension.OpCall.invoke(OpCall.groovy:166)
	at nextflow.extension.OpCall.call(OpCall.groovy:113)
	at nextflow.extension.ChannelExtensionDelegate.invokeExtensionMethod(ChannelExtensionDelegate.groovy:144)
	at groovy.runtime.metaclass.NextflowDelegatingMetaClass.invokeMethod(NextflowDelegatingMetaClass.java:60)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_733b14b3.runScript(Script_733b14b3:130)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:170)
	at nextflow.script.BaseScript.run(BaseScript.groovy:203)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:220)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:334)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)

**Comment by mashehu** [comment]
You can either run it with an extra `-dsl1` option or use the dev version (with `-r dev`) which is written in DSL2.
